# SPDX-FileCopyrightText: 2026 Jan Ingenhousz Institute
# SPDX-License-Identifier: GPL-3.0-only

"""Installed GUI identity and update-state evaluation.

The package identity is generated by CI and embedded in every PyInstaller
bundle.  Keeping it out of source avoids the old failure mode where a version
constant drifted away from the automatically selected release tag.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

from .config import FIRMWARE_REPO


GUI_TAG_RE = re.compile(r"^flash-gui-v(\d+)\.(\d+)\.(\d+)$")
GUI_ASSETS = {
    "ambyte-flash-gui-linux.zip",
    "ambyte-flash-gui-macos.zip",
    "ambyte-flash-gui-windows.zip",
}
RELEASE_INFO_NAME = "release_info.json"
RELEASES_PAGE = f"https://github.com/{FIRMWARE_REPO}/releases"


@dataclass(frozen=True)
class InstalledGuiRelease:
    """Release identity baked into a packaged GUI executable."""

    tag: str
    version: str
    source_sha: str


@dataclass(frozen=True)
class GuiUpdateStatus:
    """Comparison of the running bundle with the newest complete release."""

    state: Literal["current", "outdated", "ahead", "unknown"]
    installed: InstalledGuiRelease | None
    latest_tag: str
    latest_version: str
    release_url: str


def _version_tuple(tag: str) -> tuple[int, int, int]:
    match = GUI_TAG_RE.fullmatch(tag)
    if match is None:
        raise ValueError(f"invalid GUI release tag: {tag!r}")
    return tuple(int(part) for part in match.groups())


def release_info_path() -> Path:
    """Return the embedded metadata path in PyInstaller or a source checkout."""

    bundle_root = getattr(sys, "_MEIPASS", None)
    if bundle_root:
        return Path(bundle_root) / "flash_gui" / RELEASE_INFO_NAME
    return Path(__file__).with_name(RELEASE_INFO_NAME)


def load_installed_release(path: Path | None = None) -> InstalledGuiRelease | None:
    """Load a valid CI-generated package identity, else return ``None``.

    Missing metadata is normal for source runs and legacy packaged builds.  A
    malformed file is treated the same way so the UI can fail safe and direct
    the operator to the release page instead of crashing at startup.
    """

    try:
        payload: Any = json.loads(
            (path or release_info_path()).read_text(encoding="utf-8")
        )
    except (OSError, ValueError):
        return None
    if not isinstance(payload, dict):
        return None

    tag = payload.get("tag")
    source_sha = payload.get("source_sha")
    if (
        payload.get("schema_version") != 1
        or not isinstance(tag, str)
        or GUI_TAG_RE.fullmatch(tag) is None
        or not isinstance(source_sha, str)
        or re.fullmatch(r"[0-9a-f]{40}", source_sha) is None
    ):
        return None
    return InstalledGuiRelease(
        tag=tag,
        version=tag.removeprefix("flash-gui-v"),
        source_sha=source_sha,
    )


def pick_gui_release(releases: list[Any]) -> dict[str, Any] | None:
    """Pick the highest complete, published ``flash-gui-v*`` release."""

    candidates: list[dict[str, Any]] = []
    for release in releases:
        if not isinstance(release, dict) or release.get("draft"):
            continue
        tag = release.get("tag_name") or ""
        if GUI_TAG_RE.fullmatch(tag) is None:
            continue
        asset_names = {
            asset.get("name")
            for asset in release.get("assets") or []
            if isinstance(asset, dict)
        }
        if not GUI_ASSETS.issubset(asset_names):
            continue
        candidates.append(release)
    if not candidates:
        return None
    return max(candidates, key=lambda release: _version_tuple(release["tag_name"]))


def evaluate_update(
    installed: InstalledGuiRelease | None, releases: list[Any]
) -> GuiUpdateStatus:
    """Compare the embedded identity with the newest downloadable GUI."""

    release = pick_gui_release(releases)
    if release is None:
        raise ValueError("no complete published flash GUI release found")

    latest_tag = release["tag_name"]
    latest_version = latest_tag.removeprefix("flash-gui-v")
    release_url = (
        release.get("html_url")
        or f"https://github.com/{FIRMWARE_REPO}/releases/tag/{latest_tag}"
    )
    if installed is None:
        state: Literal["current", "outdated", "ahead", "unknown"] = "unknown"
    else:
        current = _version_tuple(installed.tag)
        latest = _version_tuple(latest_tag)
        state = "current" if current == latest else (
            "outdated" if current < latest else "ahead"
        )
    return GuiUpdateStatus(
        state=state,
        installed=installed,
        latest_tag=latest_tag,
        latest_version=latest_version,
        release_url=release_url,
    )
