# SPDX-FileCopyrightText: 2026 Jan Ingenhousz Institute
# SPDX-License-Identifier: GPL-3.0-only

"""Host timezone detection + the firmware's supported-zone table.

The device carries no tzdata: components/timezone/timezone.c compiles in its own
IANA-name -> POSIX-TZ-rule table (generated by tools/gen_tz_table.py). Since
firmware 1.10.1 that table holds the whole IANA database, so validation here is
about catching a host zone the *device build* does not know — `cfg set timezone`
fails closed with ESP_ERR_INVALID_ARG on an unknown name, which used to surface
as an unfixable "Timezone: FAIL" at verification time (America/La_Paz, 2026-08).

Never flash a zone this module rejects: the on-boarding would fail verification,
and the device would fall back to a fixed offset for scheduling.
"""

from __future__ import annotations

import datetime

from .tz_zone_table import TZDATA_VERSION, ZONES

# Mirrors k_tz_zones in components/timezone/tz_zone_table.inc; both are
# generated by tools/gen_tz_table.py and a test asserts they match.
FIRMWARE_SUPPORTED_ZONES = ZONES
FIRMWARE_TZDATA_VERSION = TZDATA_VERSION


def local_iana_zone() -> str:
    """The PC's IANA timezone name.

    tzlocal is the only reliable cross-platform way to get an IANA name (on
    Windows the OS speaks registry names, not IANA). Falls back to UTC with the
    caller expected to surface the degradation.
    """
    try:
        import tzlocal
        name = str(tzlocal.get_localzone_name() or "").strip()
        if name:
            return name
    except Exception:
        pass
    # POSIX fallback: /etc/timezone or a TZ env var that looks IANA-ish.
    import os
    tz = os.environ.get("TZ", "")
    if "/" in tz:
        return tz
    try:
        text = open("/etc/timezone", encoding="utf-8").read().strip()
        if "/" in text:
            return text
    except OSError:
        pass
    return "UTC"


def firmware_supports(zone: str) -> bool:
    return zone in FIRMWARE_SUPPORTED_ZONES


def utc_offset_label(now: datetime.datetime | None = None) -> str:
    """e.g. 'UTC+02:00' for the local clock right now."""
    now = now or datetime.datetime.now().astimezone()
    off = now.utcoffset() or datetime.timedelta(0)
    total = int(off.total_seconds())
    sign = "+" if total >= 0 else "-"
    total = abs(total)
    return f"UTC{sign}{total // 3600:02d}:{(total % 3600) // 60:02d}"
